name: Expo Client

on: [push]

jobs:
  build-ios-client:
    name: Build iOS Expo Client
    runs-on: macOS-10.14
    
    steps:
    - name: Install Nix
      run: |
        echo >> ~/.bash_profile
        curl https://nixos.org/releases/nix/nix-2.1.2/install | bash -s -- --no-daemon
        echo '. ~/.nix-profile/etc/profile.d/nix.sh' >> ~/.ci-env.sh
    - name: Install common packages
      # direnv: configures environment with .envrc files                                        
      # findutils: where, find, etc. for expo-module test                                       
      # git: circleci checkout steps                                                            
      # gnugrep: used in .envrc                                                                 
      # gnutar: used by nix commands which download channels                                    
      # gzip: used by nix commands which download channels                                      
      # openssh: circleci checkout steps                                                        
      # rsync: expo-module-scripts uses to copy template files                                  
      # xz: circleci checkout steps                                                             
      run: |
        . ~/.ci-env.sh
        nix-env -iA \
          nixpkgs.direnv \
          nixpkgs.findutils \
          nixpkgs.git \
          nixpkgs.gnugrep \
          nixpkgs.gnutar \
          nixpkgs.gzip \
          nixpkgs.openssh \
          nixpkgs.rsync \
          nixpkgs.xz
        mkdir -p ~/.config/direnv
        echo -e "[whitelist]\nprefix = [ \"$HOME\" ]" > ~/.config/direnv/config.toml
        echo 'eval "$(direnv export bash)"' >> ~/.ci-env.sh
        echo '--frozen-lockfile true' >> ~/.yarnrc
    - uses: actions/checkout@v1
    - name: Pull submodules and LFS files
      run: |
        git submodule update
        git lfs pull
    - name: Fetch CocoaPods specs
      run: curl https://cocoapods-specs.circleci.com/fetch-cocoapods-repo-from-s3.sh | bash -s cf
    - name: Generate dynamic macros
      run: |
        . ~/.ci-env.sh
        expotools ios-generate-dynamic-macros
    - name: Build iOS app for simulator
      run: |
        . ~/.ci-env.sh
        nix run expo.procps --command fastlane ios create_simulator_build
